name: cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Your Name <email@example.com>

environment:
  sdk: '>=2.7.0 <=3.0.0'

dependencies:
  reflectable: any
  dart_mssql: ^1.0.1
  marshalling: ^0.1.19
  intl: ^0.16.0
  
#  path: ^1.6.0
executables:
  
transformers:
  - reflectable:
      entry_points:
        - cli/cli.dart

dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: '>=2.6.1 <3.0.0'
  build_test: any
  pedantic: ^1.8.0
  test: ^1.6.0
